version: 2.1
orbs:
  python: circleci/python@2.1.1

workflows:
  build-app-with-test:
    jobs:
      - build-and-test
      - deploy:
          requires: 
            - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.9
        environment:
          ADMIN_USERNAME: ${ADMIN_USERNAME}
          ADMIN_PASSWORD: ${ADMIN_PASSWORD}
          APP_SECRET_KEY: ${APP_SECRET_KEY}
          CSRF_SECRET_KEY: ${CSRF_SECRET_KEY}
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            flask test
            exitcode=$?
            echo 'export TEST_EXIT_CODE=${exitcode}' >> "$BASH_ENV"
            echo ${exitcode}
            echo ${TEST_EXIT_CODE}
      - run:
          name: Set test run status based on Pytest exit code
          command: | 
            if [[ ${TEST_EXIT_CODE} == 0 ]]; then 
              echo "export TEST_RUN_STATUS='PASSED'" >> "$BASH_ENV"
            else
              echo "export TEST_RUN_STATUS='FAILED'" >> "$BASH_ENV"
            fi     
      - store_test_results:
          path: test_results
      - run:
          name: Print Test Run Status and exit code
          command: |
            echo "Test Run Status: ${TEST_RUN_STATUS}"
            if [[ $TEST_RUN_STATUS == 'PASSED' ]]; then exit 0
            else
              exit 1
            fi  


  deploy:
    docker: 
      - image: cimg/python:3.10 
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:kxpAB1mJ2tD0mXxjS/X3OOkifMYYPWMr8RQquMlV40w"
      - run:
          name: Add SSH to known hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan -H ssh.eu.pythonanywhere.com >> ~/.ssh/known_hosts
            ssh $SSH_USER@$SSH_HOST "cd yord-website; git pull";     