name: Run Unit and Functional Tests with Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-test:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Check out the repo code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run YORD Website App
        env: 
          APP_SECRET_KEY: ${{secrets.APP_SECRET_KEY}}
          CSRF_SECRET_KEY: ${{secrets.CSRF_SECRET_KEY}}
          ADMIN_USERNAME: ${{secrets.ADMIN_USERNAME}}
          ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
        run: |
          python3 app.py &

      - name: Run tests
        run: |
          flask test   

